"""Refresh provenance bindings to match current run — fixes stale commit_sha/scenario_digest/etc.

Called in CI after run_goal_verify generates .goal_attestation.json and evidence_root.
Ensures:
 - reports/environment_manifest.json: commit_sha, scenario_digest, rules_digest, checker_digest, manifest_digest
 - all 7 reports: commit_sha, scenario_digest, rules_digest, checker_digest, environment_manifest_digest, evidence_root
 - report_hash recomputed
"""
import hashlib
import json
import pathlib
import subprocess
import sys
import yaml

BASE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))
from core.scenario_compiler import compile as compile_scenarios

REPORT_NAMES = [
    "traceability_report",
    "assumptions_report",
    "parent_contract_report",
    "cross_layer_report",
    "visual_review",
    "regression_report",
    "mutation_report",
]

RULES_SEED = [
    "group.uniform_gap",
    "global.spacing.scale",
    "paint.contrast.text",
    "component.button.hit-target",
    "TARGET_OPERABLE",
    "accessibility.focus-order",
    "FOCUS_USABLE",
    "temporal.geometry-stable",
    "MODAL_INTEGRITY",
    "breakpoint.shell.direction",
]
CHECKER_FILES = [
    "gvh/verify.py",
    "gvh/extractor.py",
    "core/coverage.py",
    "core/scenario_compiler.py",
]

def sha16(data):
    return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]

def current_commit():
    return subprocess.check_output(["git","rev-parse","HEAD"], cwd=BASE).decode().strip()

def main():
    commit = current_commit()
    domain = yaml.safe_load((BASE / "supported-domain.yaml").read_text())["supported_domain"]
    scenarios = compile_scenarios(domain)
    scenario_digest = sha16(scenarios)
    rules_digest = hashlib.sha256((BASE/"supported-domain.yaml").read_bytes() + json.dumps(RULES_SEED, sort_keys=True).encode()).hexdigest()[:16]
    checker_digest = hashlib.sha256(b"".join((BASE/p).read_bytes() for p in CHECKER_FILES)).hexdigest()[:16]

    # Load attestation to get evidence_root (generated by run_goal_verify)
    attest_path = BASE / ".goal_attestation.json"
    if not attest_path.exists():
        print("FATAL: .goal_attestation.json missing — run run_goal_verify first", file=sys.stderr)
        sys.exit(1)
    attest = json.loads(attest_path.read_text())
    evidence_root = attest.get("attestation",{}).get("evidence_root")
    if not evidence_root:
        print("FATAL: evidence_root missing in attestation", file=sys.stderr)
        sys.exit(1)

    # 1) Refresh environment_manifest.json
    manifest_path = BASE / "reports" / "environment_manifest.json"
    manifest = json.loads(manifest_path.read_text())
    # preserve runtime fields that should reflect actual CI env but fill provenance digests
    manifest["commit_sha"] = commit
    manifest["scenario_digest"] = scenario_digest
    manifest["rules_digest"] = rules_digest
    manifest["checker_digest"] = checker_digest
    # recompute manifest_digest
    copy = {k:v for k,v in manifest.items() if k not in ("manifest_digest","manifest_hash_algo")}
    manifest_digest = sha16(copy)
    manifest["manifest_digest"] = manifest_digest
    manifest["manifest_hash_algo"] = "sha256:16"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True))
    print(f"manifest refreshed commit={commit[:7]} scenario={scenario_digest} rules={rules_digest} checker={checker_digest} manifest_digest={manifest_digest} evidence_root={evidence_root}")

    # 2) Refresh each report
    expected = {
        "commit_sha": commit,
        "scenario_digest": scenario_digest,
        "rules_digest": rules_digest,
        "checker_digest": checker_digest,
        "environment_manifest_digest": manifest_digest,
        "evidence_root": evidence_root,
    }
    for name in REPORT_NAMES:
        p = BASE / "reports" / f"{name}.json"
        data = json.loads(p.read_text())
        for k,v in expected.items():
            data[k] = v
        # recompute report_hash
        copy2 = {k:v for k,v in data.items() if k not in ("report_hash","report_hash_algo")}
        h = hashlib.sha256(json.dumps(copy2, sort_keys=True).encode()).hexdigest()[:16]
        data["report_hash"] = h
        data["report_hash_algo"] = "sha256:16"
        p.write_text(json.dumps(data, indent=2, sort_keys=True))
        print(f"refreshed {name} hash={h}")

    print("STRICT BINDINGS REFRESHED")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
